### ISSUE TITLE
[Bug] ... camera still accessible when toggled off

### ISSUE THREAD

**Issue by pfr-dev** [stuarthayhurst/privacy-menu-extension#13]
**Describe the issue**
Apps can still access the camera even when toggled off. 

**To Reproduce**
1. Toggle camera accessibility off in privacy menu
2. Check if app (in my case Signal for Desktop) can access camera. 

**Expected behavior**
I expected that the camera would not be accessible for video calls with the camera toggled off. 

**System information (please complete the following information):**
 - Distro: NixOS 22.11 Raccoon x86_64
 - GNOME Shell version: 42.3.1
 - Extension version: 6

**Comment by daPhipz** [comment]
How did you install Signal for Desktop? As a native package, Snap or Flatpak?

**Comment by stuarthayhurst** [comment]
Thanks for the report, if the camera is disabled if you go into Settings > Privacy > Camera, then the extension is behaving correctly.
@daPhipz Do you know if this is a native vs containerised app issue? If it is, it might be worth adding a note to the README, I'm not sure which apps GNOME has control of the webcam for.

**Comment by daPhipz** [comment]
> Do you know if this is a native vs containerised app issue?

No, I don't know for sure - but it might be worth investigating...

**Comment by stuarthayhurst** [comment]
Looking [here](https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/851), it seems only sandboxed apps can be restricted. I'll add some sort of note to the README for that.
@pfr-dev If the Settings app reflects the camera settings, you should be able to make Signal respect this by installing the sandboxed version (flatpak / snap)

**Comment by pfr-dev** [comment]
Fair enough. It's a pity though. I was hoping for a system wide software kill-switch for the camera/mic/gps etc 
I'll keep an eye out for workarounds but I don't want to use snaps or flatpaks.

Cheers

**Comment by Rmn382** [comment]
same here
thanks for your work, i highly appreciate that! 
But system wide blocking would be very nice!

**Comment by stuarthayhurst** [comment]
> same here thanks for your work, i highly appreciate that! But system wide blocking would be very nice!

I agree system wide blocking would be nice, but that would require communication with drivers and some other magic somewhere, as well as a lot of device and app-specific fixes. This extension just makes the privacy settings in GNOME more accessible, rather than having  to trawl through GNOME Settings to toggle the camera for example. If the app respects GNOME's setting, or it's properly sandboxed, it applies, otherwise it's out of scope.
