### ISSUE TITLE
[Feature request] Remove submenus to access toogle buttons

### ISSUE THREAD

**Issue by realgrm** [stuarthayhurst/privacy-menu-extension#14]
**Is your feature request related to a problem?**
Yes, Is necessary multiple clicks to verify or set on/off an option. 

**Describe the solution you'd like**
Disable submenus to the Location, Camera and Microphone options and put the toggle directly beside each of them

**Can you work on it?**
Sadly, no.

**Additional context**
- One click to verify the status of all options
- 2 clicks to set an option on/off
![image](https://user-images.githubusercontent.com/23300290/188044043-5613b524-20d4-4f98-a720-d186d582b9c9.png)

**Comment by stuarthayhurst** [comment]
Do you know of any extensions that already do that with the toggles? It'd be much quicker to add if I have a reference :)

**Comment by stuarthayhurst** [comment]
As GNOME 43 has a quick settings menu, I'll move the settings there by default and add an option to restore the current behaviour. I don't think I'll add this, as this would make it inconsistent with the current design of GNOME shell, sorry.

**Comment by stuarthayhurst** [comment]
Well, it's been a while, but I figured it out, and it'll be in the next release :)
