### ISSUE TITLE
[Bug] Power menu sometimes seem glitch

### ISSUE THREAD

**Issue by Anifyuli** [stuarthayhurst/privacy-menu-extension#20]
**Describe the issue**
Power menu sometimes seem glitch in random situation, or if new menu such LAN connected.

**To Reproduce**
1. Power menu seem glitch
2. Click to menu, such as bluetooth and solved.
3. Or close power menu to solve it.
4. Or disable and enable again to solve it.
5. Restart session to solve it.
6. Log out and login again to solve it.

**Expected behavior**
Glitch not appear

**Screenshots and logs**
![Screenshot from 2022-12-02 07-22-45](https://user-images.githubusercontent.com/73734843/205434783-71b41e3f-38e0-4322-90a2-d750ce0e1857.png)

**System information (please complete the following information):**
 - Distro: Fedora 37 Workstation Edition
 - GNOME version: 43.1
 - Extension version : 9

**Additional context**
Not yet

**Comment by stuarthayhurst** [comment]
Are you sure this extension is the reason it happens? Disabling and enabling the extension triggers a refresh of that menu, which might be why the glitch goes away when disabling and enabling the extension, even if the extension isn't the cause.

Can you reproduce the issue with the extension disabled?

**Comment by Anifyuli** [comment]
Hmmm this bug sometimes appear, and from all this way to reproduce it. I don't know why this extension cause glitch or not. In other case, if I disable all of my extension, this glitch can disappear

**Comment by stuarthayhurst** [comment]
> Sorry my English

No worries

As this happens when the extension is disabled, this isn't caused by this extension. I recommend you create a bug report in upstream GNOME, as they might be able to help you out. Link to help out: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues
