### ISSUE TITLE
[Bug] ...Flatpak apps can access camera even when toggled off

### ISSUE THREAD

**Issue by RasheedAZ** [stuarthayhurst/privacy-menu-extension#24]
**Describe the issue**
Flatpak apps can still access the camera even when toggled off.

**To Reproduce**
Steps to reproduce the behaviour:
1. Toggle camera accessibility off in privacy menu.
2. Check if flatpak app can access camera.

I tested Jitsi Meet, Chromium (with call on https://meet.jit.si), Cheese, Kamoso, Camera all from Flathub.

**Expected behaviour**
I expected that the webcam would not be accessible at all with the camera setting toggled off.

**System information (please complete the following information):**
 - Distro: Pop!_OS 22.04
 - GNOME version: 42.5
 - Extension version: 12

**Additional context**
Saw the previous issue with Signal app but that wasn't a flatpak so opened new issue.

**Comment by RasheedAZ** [comment]
> When you toggle the setting, does it match whether it's enabled / disabled inside GNOME Settings?

There appear to be no toggles for camera or microphone in privacy settings. Are these new in Gnome 43 or 44? Perhaps that's why Pop doesn't have them yet?

![Screenshot from 2023-06-07 20-22-02](https://github.com/stuarthayhurst/privacy-menu-extension/assets/16827461/3b36bf1b-c02a-4368-9aaa-7f37da468274)

**Comment by RasheedAZ** [comment]
Searching in setting doesn't give any results for camera or webcam at all. For mic, it gives results in Sound to adjust input levels but not to disable it.

**Comment by stuarthayhurst** [comment]
I can't see the settings in a VM either, it must be a patch from PopOS developers to disable them.

If the values of:
 - `gsettings get org.gnome.desktop.privacy disable-camera`
 - `gsettings get org.gnome.desktop.privacy disable-microphone`
 - `gsettings get org.gnome.system.location enabled`
All match the values reported by the extension, then the extension is behaving correctly.

I know non-sandboxed apps ignore the preference, and I think sandboxed apps can be overridden with something like Flatseal. I've also noticed that the settings are ignored more on older systems, my systems running GNOME 43 and 44 haven't had these issues. Perhaps the developers tightened up some polcies?

**Comment by stuarthayhurst** [comment]
Closing, as the extension seems to be behaving correctly. If anyone has the same issue, and the gsettings don't match what the extension is reporting, feel free to reopen :)
