### ISSUE TITLE
[Feature request] Improve interaction with the group button

### ISSUE THREAD

**Issue by rthrejheytjyrtj545** [stuarthayhurst/privacy-menu-extension#41]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
The button should indicate its state and both buttons should not be for the same action. The primary button can, instead of opening a menu, toggle all options to zero and back to the last configuration, and the button itself can appear as enabled when there are zero options enabled

**Describe alternatives you've considered**
Leave only one button without a secondary one with an arrow and mark it as enabled when any option is disabled in the menu

**Can you work on it?**
No

**Additional context**
Other buttons in GNOME Shell and Quick Settings

**Comment by stuarthayhurst** [comment]
I suppose it shouldn't be too hard to just create a callback to either open the menu or toggle all settings, and then pick which based off of the settings. I'll add this when I get time, thanks :)

**Comment by stuarthayhurst** [comment]
Right, the toggle button gets highlighted now when any of the settings are enabled, I'll add the toggle behaviour and a setting to enable that behaviour soon too.

**Comment by stuarthayhurst** [comment]
If you're comfortable installing from source, the `toggle-on-click` branch should have those covered. If that branch doesn't exit, I must've already pulled it into `master`.

If you could give this a test and let me know if I got it right, that would be great thanks :)
